---
# defaults file for java_daemon
#name_of_user: quantum                   # default root: user and group within java_service.j2

# should all have the same name
# systemd_service: /etc/systemd/system/swag.service
#
# java_daemon.j2 template
# name_of_service: swag                  # default is quantum
###########################################################
java_memory: -Xmx1024m                   # default is -Xmx512m
# java_profile: default,dev              # default is default,dev
# path_to_jar: /vagrant/                 # default is /opt/z-bin
# jar: system-server.jar                 # default is system-server.jar
